version: "3.8"

networks:
  springboot-mysql-net:

services:
  mariadb:
    container_name: mariadb
    image: "mariadb:latest"
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=kaddemproject
    networks:
      - springboot-mysql-net

  kadem:
    build:
      context: ./
      dockerfile: Dockerfile
    image: kadem
    container_name: kadem_container
    restart: unless-stopped
    environment:
      - spring.datasource.url=jdbc:mysql://mariadb:3306/kaddemproject?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8089:8086"
    depends_on:
      - mariadb
    networks:
      - springboot-mysql-net