version: '3.9'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddemProject
    networks:
      - springboot-mysql-net
    restart: always

  my-spring-app:
    container_name: my-spring-app
    image: springapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net
    restart: always

networks:
  springboot-mysql-net:
    driver: bridge
