version: '3.9'

services:
  mysqldb:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kaddemProject
    ports:
      - "3306:3306"
    networks:
      - springboot-mysql-net
    restart: always

  my-spring-app:
    container_name: my-spring-app
    image: chehinedhemaied-5twin2
    ports:
      - "9091:9091"
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net
    restart: always

networks:
  springboot-mysql-net:
    driver: bridge