version: '3.9'

services:
  mysqldb:
    container_name: mysql
    image: 'mysql:5.7'
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: malekdb
    networks:
      - springboot-mysql-net
    restart: always

  my-spring-app:
    container_name: project-spring-app-1
    image: project-spring-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - mysqldb
    networks:
      - springboot-mysql-net
    restart: always

networks:
  springboot-mysql-net:
    driver: bridge
