version: '3'

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql
    restart: unless-stopped

  my-spring-app:
    container_name: my-spring-app
    image: my-spring-app
    ports:
      - "9090:9090"
    depends_on:
      - mysql
    restart: on-failure

